server:
  port: 8070
  waitTimeInMsWhenSyncEmpty: 5
  servlet:
    context-path: /eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/