
server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/userDatabase
    password: root
    username: root

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Your Spring Boot App
    description: A sample Spring Boot application
    version: 1.0.0
    author: Your Name

example:
  property: I AM THE DEFAULT
